EVENT_TYPE_NOTE = "Note Hook"
EVENT_TYPE_PUSH = "Push Hook"
EVENT_TYPE_ISSUE = "Issue Hook"
EVENT_TYPE_PR = "Merge Request Hook"
# StatusOpen gitee issue or pr status is open
STATUS_OPEN = "open"
# StatusClosed gitee issue or pr status is closed
STATUS_CLOSED = "closed"
STATUS_MERGED = "merged"
ACTION_OPEN = "open"
ACTION_CLOSE = "close"
PR_ACTION_MERGE = "merge"
PR_ACTION_UPDATED_LABEL = "update_label"
PR_ACTION_CHANGED_TARGET_BRANCH = "target_branch_changed"
PR_ACTION_CHANGED_SOURCE_BRANCH = "source_branch_changed"
PR_ACTION_LINK_ISSUE = "update_link_issue"
ACTION_ADD_LABEL = "add_label"
