# coding: utf-8

"""
    码云 Open API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 5.3.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V5MarkdownBody1(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'access_token': 'str',
        'text': 'str'
    }

    attribute_map = {
        'access_token': 'access_token',
        'text': 'text'
    }

    def __init__(self, access_token=None, text=None):  # noqa: E501
        """V5MarkdownBody1 - a model defined in Swagger"""  # noqa: E501
        self._access_token = None
        self._text = None
        self.discriminator = None
        if access_token is not None:
            self.access_token = access_token
        self.text = text

    @property
    def access_token(self):
        """Gets the access_token of this V5MarkdownBody1.  # noqa: E501

        用户授权码  # noqa: E501

        :return: The access_token of this V5MarkdownBody1.  # noqa: E501
        :rtype: str
        """
        return self._access_token

    @access_token.setter
    def access_token(self, access_token):
        """Sets the access_token of this V5MarkdownBody1.

        用户授权码  # noqa: E501

        :param access_token: The access_token of this V5MarkdownBody1.  # noqa: E501
        :type: str
        """

        self._access_token = access_token

    @property
    def text(self):
        """Gets the text of this V5MarkdownBody1.  # noqa: E501

        Markdown 文本  # noqa: E501

        :return: The text of this V5MarkdownBody1.  # noqa: E501
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this V5MarkdownBody1.

        Markdown 文本  # noqa: E501

        :param text: The text of this V5MarkdownBody1.  # noqa: E501
        :type: str
        """
        if text is None:
            raise ValueError("Invalid value for `text`, must not be `None`")  # noqa: E501

        self._text = text

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V5MarkdownBody1, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V5MarkdownBody1):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
