# coding: utf-8

"""
    码云 Open API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 5.3.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gitee
from gitee.models.project_member_put_param import ProjectMemberPutParam  # noqa: E501
from gitee.rest import ApiException


class TestProjectMemberPutParam(unittest.TestCase):
    """ProjectMemberPutParam unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectMemberPutParam(self):
        """Test ProjectMemberPutParam"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gitee.models.project_member_put_param.ProjectMemberPutParam()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
