# coding: utf-8

"""
    码云 Open API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 5.3.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gitee
from gitee.models.messages_id_body1 import MessagesIdBody1  # noqa: E501
from gitee.rest import ApiException


class TestMessagesIdBody1(unittest.TestCase):
    """MessagesIdBody1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMessagesIdBody1(self):
        """Test MessagesIdBody1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gitee.models.messages_id_body1.MessagesIdBody1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
