# coding: utf-8

"""
    码云 Open API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 5.3.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import gitee
from gitee.models.repo_patch_param import RepoPatchParam  # noqa: E501
from gitee.rest import ApiException


class TestRepoPatchParam(unittest.TestCase):
    """RepoPatchParam unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRepoPatchParam(self):
        """Test RepoPatchParam"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gitee.models.repo_patch_param.RepoPatchParam()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
