# coding: utf-8

"""
    码云 Open API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 5.3.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gitee
from gitee.models.labels_original_name_body1 import LabelsOriginalNameBody1  # noqa: E501
from gitee.rest import ApiException


class TestLabelsOriginalNameBody1(unittest.TestCase):
    """LabelsOriginalNameBody1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLabelsOriginalNameBody1(self):
        """Test LabelsOriginalNameBody1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gitee.models.labels_original_name_body1.LabelsOriginalNameBody1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
