# coding: utf-8

"""
    码云 Open API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 5.3.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gitee
from gitee.models.label_post_param import LabelPostParam  # noqa: E501
from gitee.rest import ApiException


class TestLabelPostParam(unittest.TestCase):
    """LabelPostParam unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLabelPostParam(self):
        """Test LabelPostParam"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gitee.models.label_post_param.LabelPostParam()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
