# coding: utf-8

"""
    码云 Open API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 5.3.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gitee
from gitee.models.contents_path_body import ContentsPathBody  # noqa: E501
from gitee.rest import ApiException


class TestContentsPathBody(unittest.TestCase):
    """ContentsPathBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContentsPathBody(self):
        """Test ContentsPathBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gitee.models.contents_path_body.ContentsPathBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
