# coding: utf-8

"""
    码云 Open API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 5.3.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gitee
from gitee.models.v5_gists_body import V5GistsBody  # noqa: E501
from gitee.rest import ApiException


class TestV5GistsBody(unittest.TestCase):
    """V5GistsBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV5GistsBody(self):
        """Test V5GistsBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gitee.models.v5_gists_body.V5GistsBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
