# coding: utf-8

"""
    码云 Open API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 5.3.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gitee
from gitee.models.pull_request_assignee_post_param import PullRequestAssigneePostParam  # noqa: E501
from gitee.rest import ApiException


class TestPullRequestAssigneePostParam(unittest.TestCase):
    """PullRequestAssigneePostParam unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPullRequestAssigneePostParam(self):
        """Test PullRequestAssigneePostParam"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gitee.models.pull_request_assignee_post_param.PullRequestAssigneePostParam()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
