# coding: utf-8

"""
    码云 Open API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 5.3.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gitee
from gitee.models.following_username_body1 import FollowingUsernameBody1  # noqa: E501
from gitee.rest import ApiException


class TestFollowingUsernameBody1(unittest.TestCase):
    """FollowingUsernameBody1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFollowingUsernameBody1(self):
        """Test FollowingUsernameBody1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gitee.models.following_username_body1.FollowingUsernameBody1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
