# coding: utf-8

"""
    码云 Open API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 5.3.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import gitee
from gitee.api.git_data_api import GitDataApi  # noqa: E501
from gitee.rest import ApiException


class TestGitDataApi(unittest.TestCase):
    """GitDataApi unit test stubs"""

    def setUp(self):
        self.api = gitee.api.git_data_api.GitDataApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_v5_repos_owner_repo_git_blobs_sha(self):
        """Test case for get_v5_repos_owner_repo_git_blobs_sha

        获取文件Blob  # noqa: E501
        """
        pass

    def test_get_v5_repos_owner_repo_git_trees_sha(self):
        """Test case for get_v5_repos_owner_repo_git_trees_sha

        获取目录Tree  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
