# coding: utf-8

"""
    码云 Open API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 5.3.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from gitee.configuration import Configuration


class Note(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'body': 'str',
        'body_html': 'str',
        'user': 'User',
        'source': 'str',
        'created_at': 'str',
        'target': 'str'
    }

    attribute_map = {
        'id': 'id',
        'body': 'body',
        'body_html': 'body_html',
        'user': 'user',
        'source': 'source',
        'created_at': 'created_at',
        'target': 'target'
    }

    def __init__(self, id=None, body=None, body_html=None, user=None, source=None, created_at=None, target=None, _configuration=None):  # noqa: E501
        """Note - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._body = None
        self._body_html = None
        self._user = None
        self._source = None
        self._created_at = None
        self._target = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if body is not None:
            self.body = body
        if body_html is not None:
            self.body_html = body_html
        if user is not None:
            self.user = user
        if source is not None:
            self.source = source
        if created_at is not None:
            self.created_at = created_at
        if target is not None:
            self.target = target

    @property
    def id(self):
        """Gets the id of this Note.  # noqa: E501


        :return: The id of this Note.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Note.


        :param id: The id of this Note.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def body(self):
        """Gets the body of this Note.  # noqa: E501


        :return: The body of this Note.  # noqa: E501
        :rtype: str
        """
        return self._body

    @body.setter
    def body(self, body):
        """Sets the body of this Note.


        :param body: The body of this Note.  # noqa: E501
        :type: str
        """

        self._body = body

    @property
    def body_html(self):
        """Gets the body_html of this Note.  # noqa: E501


        :return: The body_html of this Note.  # noqa: E501
        :rtype: str
        """
        return self._body_html

    @body_html.setter
    def body_html(self, body_html):
        """Sets the body_html of this Note.


        :param body_html: The body_html of this Note.  # noqa: E501
        :type: str
        """

        self._body_html = body_html

    @property
    def user(self):
        """Gets the user of this Note.  # noqa: E501


        :return: The user of this Note.  # noqa: E501
        :rtype: User
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this Note.


        :param user: The user of this Note.  # noqa: E501
        :type: User
        """

        self._user = user

    @property
    def source(self):
        """Gets the source of this Note.  # noqa: E501


        :return: The source of this Note.  # noqa: E501
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this Note.


        :param source: The source of this Note.  # noqa: E501
        :type: str
        """

        self._source = source

    @property
    def created_at(self):
        """Gets the created_at of this Note.  # noqa: E501


        :return: The created_at of this Note.  # noqa: E501
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this Note.


        :param created_at: The created_at of this Note.  # noqa: E501
        :type: str
        """

        self._created_at = created_at

    @property
    def target(self):
        """Gets the target of this Note.  # noqa: E501


        :return: The target of this Note.  # noqa: E501
        :rtype: str
        """
        return self._target

    @target.setter
    def target(self, target):
        """Sets the target of this Note.


        :param target: The target of this Note.  # noqa: E501
        :type: str
        """

        self._target = target

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Note, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Note):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Note):
            return True

        return self.to_dict() != other.to_dict()
